### ISSUE TITLE
AT: Janssen Booster Covid Certificates fail verification

### ISSUE THREAD

**Issue by stoconnor** [eu-digital-green-certificates/dgc-business-rules-testdata#100]
Booster certificates where the original vaccine was Janssen fails verification in AT rules

The Digital Covid Certificate appears as 2 of 1 doses. Number of doses is 2 and Total doses is 1 where it refers total doses of the vaccine used for a booster.

The certificate is as per European recommendation set out here:

https://ec.europa.eu/commission/presscorner/detail/en/ip_21_6837

"Boosters will be recorded as follows:

3/3 for a booster dose following a primary 2-dose vaccination series.
2/1 for a booster dose following a single-dose vaccination or a one dose of a 2-dose vaccine administered to a recovered person"

**Comment by dslmeinte** [comment]
Hi @stoconnor Are you one of the developers of the business rules for AT?

If not: This repo is for development/staging purposes _only_, so there's no requirement that all rules should follow all EU regulations at all times. I'm quite sure that developers of business rules for AT are already aware of this regulation, and already planning to update their rules - at least on the EU DCC Gateway itself, and possibly here as well.

**Comment by stoconnor** [comment]
Thanks for the update. I'm not a developer for business rules for AT, I was looking to raise awareness of this issue but sounds like it's in progress. I'll close out this issue
