### ISSUE TITLE
Wrong entry rules for Malta

### ISSUE THREAD

**Issue by Ein-Tim** [eu-digital-green-certificates/dgc-business-rules-testdata#105]
## Describe the bug

The entry rules / BNR are wrong for Malta. It rejects all certificates as invalid if they are older than 90 days, however, according to https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/eu-digital-covid-certificate_en the validity period of 270 days is binding.
Malta also states that the 270 days is actually the rule (see https://deputyprimeminister.gov.mt/en/health-promotion/covid-19/Documents/Standards_vaccine_certificate_validity_100322_clean.pdf).

## Steps to reproduce the issue

Should be clear, you have to use a certificate of a person which is older than 18 years & which is not a booster certificate.

## Expected behaviour

Malta should have rules which complies with the actual rules set by the country.

**Comment by Ein-Tim** [comment]
Ping @georgekutty23

**Comment by Ein-Tim** [comment]
Here is the result when a certificate is checked with the German Corona-Warn-App:

<img src="https://user-images.githubusercontent.com/67682506/159850449-0b74fb09-46c2-4100-a9ad-77a7c68634eb.png" width="300">

**Comment by dslmeinte** [comment]
Thanks for raising the issue. I've sent @georgekutty23 an email. Ultimately, it's up to Malta to fix this.

This repository is purely for development purposes, and its maintainers have no direct influence on what's published on the EU DCC Gateway. I'll close the issue, but will reference it.

**Comment by dslmeinte** [comment]
Hi @Ein-Tim ,

There's no such repository because no one repository could serve as the authoritative source of these business rules: that'd be the official EU DCC Gateway (PROD). (The Gateway is open source, but has wider functionality than just rules, so its repo wouldn't be suitable either.)

Could you contact me per email (meinte.boersma at gmail) to discuss this further?

**Comment by dslmeinte** [comment]
Malta has updated their business rules: booster vaccinations are now accepted. However, the 90 vs. 270 days discrepancy is still there.

**Comment by Ein-Tim** [comment]
@dslmeinte 

Thanks! Did they say if the will address this?

**Comment by dslmeinte** [comment]
@Ein-Tim I alerted them to the issues with the max. validity this morning again, but have to hear back from them.
