### ISSUE TITLE
[EU, NL, FI] Validation of recovery validation time is done on df and du fields rather than fr

### ISSUE THREAD

**Issue by ikbendewilliam** [eu-digital-green-certificates/dgc-business-rules-testdata#18]
For EU, NL and FI rules the validation of recovery is done based upon the fields `df` and `du`. This means that a country with different rules in their certificate are not valid.
I believe this validation should solely be based upon the `fr` field (as DE does correct).

Since these are the template/recommendation rules, I believe this will cause issues

Rules of DE: 
https://github.com/eu-digital-green-certificates/dgc-business-rules-testdata/blob/main/DE/RR-DE-0002/rule.json
https://github.com/eu-digital-green-certificates/dgc-business-rules-testdata/blob/main/DE/RR-DE-0001/rule.json
Rules of EU, NL and FI:
https://github.com/eu-digital-green-certificates/dgc-business-rules-testdata/blob/main/EU/RR-EU-0001/rule.json - This means that a country that has more strict rules than your country are validation rather than the local rules
https://github.com/eu-digital-green-certificates/dgc-business-rules-testdata/blob/main/EU/RR-EU-0002/rule.json - This means that a country that has less strict rules than your country are invalid and not able to enter
https://github.com/eu-digital-green-certificates/dgc-business-rules-testdata/blob/main/FI/RR-FI-0001/rule.json
https://github.com/eu-digital-green-certificates/dgc-business-rules-testdata/blob/main/FI/RR-FI-0004/rule.json
https://github.com/eu-digital-green-certificates/dgc-business-rules-testdata/blob/main/NL/RR-NL-0001/rule.json
https://github.com/eu-digital-green-certificates/dgc-business-rules-testdata/blob/main/NL/RR-NL-0004/rule.json

**Comment by dslmeinte** [comment]
Correct observation. However, Member States are free to determine their own fit-for-entry rules. Also, this repository is for development/pre-production(/staging) purposes only, so nothing in here has any official status. In particular, “fixing” this problem through a PR on this repo most likely has 0 effect on the actual rules implemented, because there's no automatic/direct from the rules in this repo to the actual ones.

**Comment by ikbendewilliam** [comment]
The reason I encountered this was that we've used the EU rules as a template for the Belgian validation rules. During some initial testing we encountered an invalid recovery certificate (which was valid, but due to an incorrect expiration date since it was an example certificate, the rules flagged the certificate as invalid). 
I wanted to mention this, since other countries might also use the EU-rules as a template and miss this 😃.

**Comment by dslmeinte** [comment]
Could you have a look at this app?: [https://dcc-crosscheck.vercel.app/](https://dcc-crosscheck.vercel.app/)
Is it useful for you?

**Comment by chris-baumann-at** [comment]
> Could you have a look at this app?: https://dcc-crosscheck.vercel.app/
> Is it useful for you?

YES!!! Absolutely!
Thx

**Comment by chris-baumann-at** [comment]
> 
> Could you have a look at this app?: https://dcc-crosscheck.vercel.app/

You can feed the dcc-crosscheck with data from https://test.baumann.at/hcert-gen/ ...
