### ISSUE TITLE
Problem with certificate validity check when checking against France

### ISSUE THREAD

**Issue by Ein-Tim** [eu-digital-green-certificates/dgc-business-rules-testdata#87]
## Technical details

- Device name: iPhone XR / Huawei P Smart 2019
- iOS/Android version: 15.2 / 10
- Apps used to test: CovPass (Germany) & Corona-Warn-App (Germany)

## Describe the bug

Checking any vaccination certificate against validity for entry to France fails with the error "Only test is allowed, and in a EU standard format." Rule ID: GR-FR-0000 (1.0.3)

## Steps to reproduce the issue

1. Add a vaccination certificate to your wallet app supporting validity checks
2. Check the validity against France
3. See the issue described above

## Expected behaviour

According to https://de.ambafrance.org/COVID-19-Kann-ich-nach-Frankreich-einreisen I'm allowed to travel to France with my vaccination certificate, so I'm not sure why it's shown as invalid. Probably France made a mistake when updating the rules?

## Pings 

@mkubicek-dtc you [initially added](https://github.com/eu-digital-green-certificates/dgc-business-rules-testdata/commit/b4bfb012889698f050966132622e3b2bd6dda8a8#diff-501c26b2571a1f7fd72df8c21593874fc874c97145717470596895d1c22203f7) the business rules testdata, so you may be able to confirm that this is not intended and transfer this issue to the responsible colleagues?

FYI (CWA/CovPass): @thomasaugsten, @mlenkeit, @dsarkar ,@timokoenig & @vaubaehn

**Comment by timokoenig** [comment]
The rule is a general rule ( https://distribution.dcc-rules.de/rules/FR/41b2e96f02c9fa8ff2a7f9d10086bd3d3f1cb3a7bf1385897941c4d775551654 ) which does get applied to all certificate types (vaccination, test, recovery). Maybe this was intended to be a rule for test certificates only?

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-11048](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11048)

**Comment by vaubaehn** [comment]
Also pinging @lovasoa in cc: as that person uploaded the latest FR-business-rules testdata.

**Comment by vaubaehn** [comment]
> Maybe this was intended to be a rule for test certificates only?

Yes, it looks like it was intended to replace TR-FR-0000.

**Comment by lovasoa** [comment]
Hi ! I'm the author of the independant open-source dgc reader [sanipasse](https://sanipasse.fr), but I don't work for the french government.

**Comment by vaubaehn** [comment]
Hi @lovasoa ,
sorry for my misguided ping in this case.
Stay well and healthy,
cordialement,
v.

**Comment by dslmeinte** [comment]
> Hi ! I'm the author of the independant open-source dgc reader [sanipasse](https://sanipasse.fr), but I don't work for the french government.

Awesome effort, by the way: many thanks for doing that!

**Comment by Ein-Tim** [comment]
This issue has been fixed. Closing.
